name: rotation_ball_view_example
description: Demo app for rotation_ball_view.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  rotation_ball_view:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
